# Generated by Django 3.0.6 on 2021-03-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(help_text='Shop Name', max_length=50)),
                ('tenant_name', models.CharField(help_text='Shop owner name', max_length=50)),
                ('rent', models.FloatField(help_text='Monthly rent')),
                ('datetime', models.DateTimeField(help_text='Contract ending date')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
